environment: stg
enableDeployment: false

deployment:
  containersExtra:
    - name: todo_change_me-sql-proxy
      image: gcr.io/cloudsql-docker/gce-proxy:1.11
      ports:
        - name: proxy-port
          containerPort: 5432
      command:
        - ./cloud_sql_proxy
        - -instances=todo_change_me
  appendEnv:
    - name: DB_SERVER_URL
      value: "jdbc:postgresql://localhost:5432/ads-kotlin-service-template"
    - name: DB_USERNAME
      value: "ads-kotlin-service-template"
    - name: DB_PASSWORD
      value: "{{vault-secret secret/todo_change_me/DB_PASSWORD}}"
    - name: NATS_SERVERS
      value: "nats-0.c.unity-ads-nats-stg.internal:4222,nats-1.c.unity-ads-nats-stg.internal:4222,nats-2.c.unity-ads-nats-stg.internal:4222"
