# Helm setup is based on https://gitlab.internal.unity3d.com/unimatrix/unity-common-chart/
enableDeployment: false
enableService: true
enableVaultSecrets: true

namespace: todo_change_me
productgroup: todo_change_me

deployment:
  nodeSelector:
    service: "todo_change_me"
  tolerations:
  - key: "service"
    operator: "Equal"
    value: "todo_change_me"
    effect: "NoSchedule"
  args: ["java", "-XX:MaxRAMPercentage=90", "-jar", "/ads-kotlin-service-template/ads-kotlin-service-template.jar"]
  replicas: 2
  image:
    repository: gcr.io/unity-ads-common-prd/ads-kotlin-service-template
    tag: master
  resources:
    requests:
      cpu: 0.2
      memory: 256Mi
    limits:
      cpu: 1
      memory: 1024Mi
  livenessProbe:
    port: 8080
    path: /live
    initialDelaySeconds: 3
    timeoutSeconds: 5
  readinessProbe:
    port: 8080
    path: /live
    initialDelaySeconds: 3
    timeoutSeconds: 5
service:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 30253
      targetPort: 8080
    - name: internal
      protocol: TCP
      port: 30254
      targetPort: 8081
